#!/usr/bin/env python3
"""Regenerates bba-lessons.js — the lesson titles of the three vocabulary
sites, so the teacher dashboard can print "U6.1 · Les grandes fêtes" and
"Y8U4.3 · ir and opinions" rather than a bare code.

Le Lexique and El Léxico keep their words in data/corpus.js; the KS3–KS4 site
keeps one file per list and a contents page in data/index.js, so it is read
from there. Run from the folder that holds the site repositories."""
import re, json, os
here = os.path.dirname(os.path.abspath(__file__)); root = os.path.dirname(here)
out = {}

for lang, repo in (("FR", "A-Level-French-Edexcel-Vocab-training"),
                   ("ES", "A-Level-Spanish-Edexcel-Vocabulary-training")):
    s = open(os.path.join(root, repo, "data", "corpus.js"), encoding="utf-8").read()
    d = {}
    for m in re.finditer(r'"lesson":\s*"([^"]+)",\s*"lessonTitle":\s*"((?:[^"\\]|\\.)*)"', s):
        d.setdefault(m.group(1), json.loads('"' + m.group(2) + '"'))
    out[lang] = d

ks = os.path.join(root, "KS3-KS4-Spanish-Vocabulary-training", "data", "index.js")
if os.path.exists(ks):
    s = open(ks, encoding="utf-8").read()
    idx = json.loads(s[s.index("{"):s.rindex("}") + 1])
    out["KS"] = {L["l"]: L["t"] for u in idx.get("units", []) for L in u.get("lessons", [])}

js = ("/* Lesson titles for the vocabulary sites, generated by build-lessons.py\n"
      "   from each site's data folder. Regenerate when lists are added. */\n"
      "window.BBA_LESSONS = " + json.dumps(out, ensure_ascii=False) + ";\n")
open(os.path.join(here, "bba-lessons.js"), "w", encoding="utf-8", newline="\n").write(js)
print({k: len(v) for k, v in out.items()})
